apiVersion: v1
kind: Service
metadata:
  name: app-2-service
spec:
  selector:
    app: app-2 # Label selector to select pods from the app-2 Deployment
  ports:
    - protocol: TCP
      port: 8080 # The port on which the service will be exposed
      targetPort: 3000  # The port on the pods that the service will forward traffic to
