apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-dep
spec: #describes desired state of deployment
  replicas: 5 #5 instances of nginx service runnin
  selector:
    matchLabels:
      app: nginx #specifying labels 
      run: nginx-svc
  template:
    metadata:
      labels:
        app: nginx
        run: nginx-svc
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 
        ports:
        - containerPort: 80
        
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.cfg
      volumes: #volume that can be mounted into pods
      - name: config-volume
        configMap:
          name: nginx-configmap
          items:
          - key: nginx.cfg
            path: nginx.cfg