apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx  # Label selector to select pods from the nginx Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80