apiVersion: networking.k8s.io/v1
kind: Ingress #ingress defines routhing rules for external http or https traffic
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary-weight: "30" #30% of traffic directed to this Ingress and rewriting to req path "/"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80


